sudo: false
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk12
  - oraclejdk8
  - oraclejdk11
  - oraclejdk12
after_success:
  - mvn jacoco:report -Dgpg.skip=true
  - bash <(curl -s https://codecov.io/bash)
